FelhasznaloiFelulet/Controllers/BankController.cs
using FelhasznaloiFelulet.Data;
using FelhasznaloiFelulet.Models;
using Microsoft.AspNetCore.Mvc;

namespace FelhasznaloiFelulet.Controllers
{
    public class BankController : Controller
    {
        private readonly ApplicationDbContext _db;
        public BankController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Bank> objBankList = _db.Bank.ToList();
            return View(objBankList);
        }
        //GET
        public IActionResult AddNewBank()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNewBank(Bank obj)
        {
            if (obj.Swift != null)
            {
                var bankFromDb = _db.Bank.Find(obj.Swift.ToUpper());
                if (bankFromDb == null)
                {
                    if (obj.Name == null || obj.SeatAddress == null)
                    {
                        TempData["error"] = "Az összes mező kitöltése kötelező!";
                        return View(obj);
                    }
                    if (ModelState.IsValid)
                    {
                        _db.Bank.Add(obj);
                        _db.SaveChanges();
                        TempData["Success"] = "Az új bank hozzá lett adva!";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["error"] = "A bank SWIFT kód alapján már szerepel a rendszerben!";
                    //ModelState.AddModelError("SzerepelError", "A bank SWIFT kód alapján már szerepel a rendszerben!");
                }
            }
            else
            {
                TempData["error"] = "A Bank SWIFT kódját kötelező megadni!";
                //ModelState.AddModelError("SwiftKellError", "A Bank SWIFT kódját kötelező megadni!");
            }
            
            return View(obj);
        }
        //GET
        public IActionResult EditBank(String swift)
        {
            if(swift == null)
            {
                TempData["error"] = "Az adott bank nem található!";
                return RedirectToAction("Index");
            }
            Bank bank = _db.Bank.Find(swift);

            if(bank == null)
            {
                TempData["error"] = "Az adott bank nem található!";
                return RedirectToAction("Index");
            }
            return View(bank);
        }
        //POST
        [HttpPost]
        public IActionResult EditBank(Bank obj)
        {
            if(obj.Name == null || obj.Swift == null || obj.SeatAddress == null)
            {
                TempData["error"] = "Az összes mező kitöltése kötelező!";
                return View(obj);
            }
            if (ModelState.IsValid)
            {
                _db.Bank.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "A bank sikeresen frissítve lett!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

FelhasznaloiFelulet/Controllers/UsersController.cs
using FelhasznaloiFelulet.Data;
using FelhasznaloiFelulet.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Web;
using System;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace FelhasznaloiFelulet.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UsersController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpPost]
        public IActionResult Index(Users searchObj)
        {
            var lastName = searchObj.Lastname;
            var firstName = searchObj.Firstname;
            var swift = searchObj.BankSwift;
            var countryID = searchObj.UserAddress.CountryID;
            var city = searchObj.UserAddress.City;
            if(swift == "null")
            {
                swift = null;
            }
            if (countryID == "null")
            {
                countryID = null;
            }
            IEnumerable<Users> objUsersList;
            IEnumerable<Address> objAddressList;
            objUsersList = _db.Users.ToList();
            objAddressList = _db.Address.ToList();
            foreach (var obj in objUsersList)
            {
                Address address = _db.Address.Find(obj.ID);
                Bank bank = _db.Bank.Find(obj.BankSwift);
                Countries country = _db.Countries.Find(address.CountryID);
                address.Country = country;
                obj.UserAddress = address;
                obj.UserBank = bank;
            }
            //if (lastName == null && firstName == null && swift == null && countryID == null && city == null)
            //{
            //    return RedirectToAction("Index");
            //}
                if (lastName != null)
                {
                    objUsersList = objUsersList.Where(u => u.Lastname == lastName);
                }
                if (firstName != null)
                {
                    objUsersList = objUsersList.Where(u => u.Firstname == firstName);
                }
                if (swift != null)
                {
                    objUsersList = objUsersList.Where(u => u.BankSwift == swift);
                }
                if (countryID != null)
                {
                    objUsersList = objUsersList.Where(u => u.UserAddress.CountryID == countryID);
                }
                if (city != null)
                {
                    objUsersList = objUsersList.Where(u => u.UserAddress.City == city);
                }
            ViewData["userList"] = objUsersList;
            IEnumerable<Countries> objCountriesList = _db.Countries.ToList();
            ViewData["Countries"] = objCountriesList;
            IEnumerable<Bank> objBankList = _db.Bank.ToList();
            ViewData["Banks"] = objBankList;
            return View();
        }
        public IActionResult EditUser(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFromDb = _db.Users.Find(id);

            if (userFromDb == null)
            {
                return NotFound();
            }

            Address address = _db.Address.FirstOrDefault(a => a.ID == id);
            Bank bank = _db.Bank.Find(userFromDb.BankSwift);
            Countries country = _db.Countries.Find(address.CountryID);
            address.Country = country;
            userFromDb.UserBank = bank;
            userFromDb.UserAddress = address;
            userFromDb.UserAddress.ID = id;

            IEnumerable<Countries> objCountriesList = _db.Countries.ToList();
            ViewData["Countries"] = objCountriesList;
            IEnumerable<Bank> objBankList = _db.Bank.ToList();
            ViewData["Banks"] = objBankList;

            return View(userFromDb);
        }
        [HttpPost]
        public IActionResult EditUser(Users obj, Address objAddress, int id, int addressid)
        {
            if (obj.UserAddress.City == null || obj.UserAddress.Number == null)
            {
                TempData["error"] = "Minden mező kitöltése kötelező!";
                return RedirectToAction("AddUser");
            }
            if (ModelState.IsValid)
            {
                objAddress = _db.Address.FirstOrDefault(a => a.ID == addressid);
                objAddress.City = obj.UserAddress.City;
                objAddress.Number = obj.UserAddress.Number;
                Countries country = _db.Countries.Find(obj.UserAddress.Country.ID);
                objAddress.Country = country;

                Bank bank = _db.Bank.Find(obj.BankSwift);
                obj.UserBank = bank;
                obj.UserAddress = objAddress;

                _db.Users.Update(obj);
                _db.Address.Update(objAddress);
                _db.SaveChanges();
                TempData["success"] = "A felhasználó szerkesztve lett!";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Minden mező kitöltése kötelező!";
            return RedirectToAction("EditUser",obj);
        }
        public IActionResult Index()
        {

            IEnumerable<Users> objUsersList = _db.Users.ToList();
            IEnumerable<Address> objAddressList = _db.Address.ToList();
            foreach (var obj in objUsersList)
            {
                Address address = _db.Address.FirstOrDefault(a => a.ID == obj.UserAddress.ID);
                Bank bank = _db.Bank.Find(obj.BankSwift);
                Countries country = _db.Countries.Find(address.CountryID);
                address.Country = country;
                obj.UserAddress = address;
                obj.UserBank = bank;
            }
            ViewData["userList"] = objUsersList;
            IEnumerable<Countries> objCountriesList = _db.Countries.ToList();
            ViewData["Countries"] = objCountriesList;
            IEnumerable<Bank> objBankList = _db.Bank.ToList();
            ViewData["Banks"] = objBankList;
            return View();
        }
        //GET
        public IActionResult AddUser()
        {
            IEnumerable<Countries> objCountriesList = _db.Countries.ToList();
            ViewData["Countries"] = objCountriesList;
            IEnumerable<Bank> objBankList = _db.Bank.ToList();
            ViewData["Banks"] = objBankList;
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUser(Users obj, Address objAddress) 
        {
            if(obj.UserAddress.City == null || obj.UserAddress.Number == null)
            {
                TempData["error"] = "Az összes mező kitöltése kötelező!";
                return RedirectToAction("AddUser");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    objAddress.City = obj.UserAddress.City;
                    objAddress.Number = obj.UserAddress.Number;
                    Countries country = _db.Countries.Find(obj.UserAddress.Country.ID);
                    objAddress.Country = country;

                    Bank bank = _db.Bank.Find(obj.BankSwift);
                    obj.UserBank = bank;
                    obj.UserAddress = objAddress;

                    _db.Users.Add(obj);
                    _db.Address.Add(objAddress);
                    _db.SaveChanges();
                    TempData["success"] = "Az új felhasználó létre lett hozva!";
                    return RedirectToAction("Index");
                }
                TempData["error"] = "Az összes mező kitöltése kötelező!";
                return RedirectToAction("AddUser");
            }
        }
        //[Route("Users/CreateJson/lista")]
        //IEnumerable<Users> lista
        public IActionResult CreateJson()
        {
            IEnumerable<Users> objUsersList = _db.Users.ToList();
            IEnumerable<Address> objAddressList = _db.Address.ToList();
            foreach (var obj in objUsersList)
            {
                Address address = _db.Address.AsNoTracking().SingleOrDefault(a => a.ID == obj.ID);
                Bank bank = _db.Bank.AsNoTracking().SingleOrDefault(b => b.Swift == obj.BankSwift);
                Countries country = _db.Countries.AsNoTracking().SingleOrDefault(c => c.ID == address.CountryID);
                address.Country = country;
                obj.UserAddress = address;
                obj.UserBank = bank;
            }
            Object users = objUsersList as Object;

            //Object users = lista as Object;
            //Object users = lista;

            var json = JsonConvert.SerializeObject(users, Formatting.Indented);
            

            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);

            writer.Write(json);
            writer.Flush();
            stream.Position = 0;
            TempData["success"] = "A JSON fájl létre lett hozva!";
            return File(stream, "text/json", "jsondata.json");
            
            //return RedirectToAction("Index");

        }
        public IActionResult DeleteUser(int id, int addressid)
        {
            Users user = _db.Users.FirstOrDefault(u => u.ID == id);
            Address address = _db.Address.FirstOrDefault(a => a.ID == addressid);

            _db.Address.Remove(address);
            _db.Users.Remove(user);
            _db.SaveChanges();
            TempData["success"] = "A felhasználó törölve lett az adatbázisból!";

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult ReadFromJson(IFormCollection form, IFormFile postedFile)
        {
            using (var ms = new MemoryStream())
            {
                postedFile.CopyTo(ms);
                var fileBytes = ms.ToArray();
                string s = Convert.ToBase64String(fileBytes);
                // act on the Base64 data

                byte[] data = Convert.FromBase64String(s);

FelhasznaloiFelulet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FelhasznaloiFelulet</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FelhasznaloiFelulet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <div class="collapse" id="navbarToggleExternalContent">
          <div class="bg-dark p-4">
            <h5 class="text-white h4">Felhasználói menü</h5>
            <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="listText nav-link text" asp-area="" asp-controller="Home" asp-action="Index">Főoldal</a>
                        </li>
                        <li class="nav-item">
                            <a class="listText nav-link text" asp-area="" asp-controller="Bank" asp-action="Index">Bankok megtekintése</a>
                        </li>
                        <li class="nav-item">
                            <a class="listText nav-link text" asp-area="" asp-controller="Users" asp-action="Index">Felhasználók listázása</a>
                        </li>
                    </ul>
          </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </nav>

   </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="text" style="color: white !important">
                &copy; 2022 - Felhasználói felület - <a id="privacyLink" asp-area="" asp-controller="Home" asp-action="Privacy">Adatvédelem</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/showdatas.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FelhasznaloiFelulet/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}